- pkg/service/ddosx/error.go
- pkg/service/ddosx/model.go
- pkg/service/ddosx/model_test.go
- pkg/service/ddosx/request.go
- pkg/service/ddosx/request_test.go
- pkg/service/ddosx/response.go
- pkg/service/ddosx/service.go
- pkg/service/ddosx/service_domain.go
- pkg/service/ddosx/service_domain_test.go
This PR adds DDoSX Domain HSTS configuration support
> Hstsconfiguration additions

- pkg/service/ddosx/service.go
- pkg/service/ddosx/service_domain.go
- pkg/service/ddosx/service_domain_test.go
This PR adds support for deleting DDoSX domains
> Adds support for deleting DDoSX domains

- pkg/service/pss/request.go
- pkg/service/pss/service.go
- pkg/service/pss/service_request.go
- pkg/service/pss/service_request_test.go
Adds additional PSS resources:
- Create request
- Update request
- Create request reply
> add additional pss resources

- pkg/service/account/error.go
- pkg/service/account/model.go
- pkg/service/account/model_paginated.go
- pkg/service/account/response.go
- pkg/service/account/service.go
- pkg/service/account/service_invoice.go
- pkg/service/account/service_invoice_test.go
This PR adds support for retrieving account invoices
> adds support for retrieving account invoices

- pkg/service/account/error.go
- pkg/service/account/model.go
- pkg/service/account/model_paginated.go
- pkg/service/account/request.go
- pkg/service/account/response.go
- pkg/service/account/service.go
- pkg/service/account/service_invoice.go
- pkg/service/account/service_invoice_test.go
This PR adds support for account invoice queries
> adds support for account invoice queries

- pkg/service/ltaas/model.go
- pkg/service/ltaas/request.go
- pkg/service/ltaas/service.go
- pkg/service/ltaas/service_domain.go
- pkg/service/ltaas/service_domain_test.go
- pkg/service/ltaas/service_job_test.go
This PR adds remainder of LTaaS domain methods
> LTaaS Domain methods

- pkg/service/ecloud/error.go
- pkg/service/ecloud/model.go
- pkg/service/ecloud/model_paginated_generated.go
- pkg/service/ecloud/model_response_generated.go
- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_availabilityzone.go
- pkg/service/ecloud/service_availabilityzone_test.go
- pkg/service/ecloud/service_dhcp.go
- pkg/service/ecloud/service_dhcp_test.go
- pkg/service/ecloud/service_firewallrule.go
- pkg/service/ecloud/service_firewallrule_test.go
- pkg/service/ecloud/service_floatingip.go
- pkg/service/ecloud/service_floatingip_test.go
- pkg/service/ecloud/service_instance.go
- pkg/service/ecloud/service_instance_test.go
- pkg/service/ecloud/service_loadbalancercluster.go
- pkg/service/ecloud/service_loadbalancercluster_test.go
- pkg/service/ecloud/service_network.go
- pkg/service/ecloud/service_network_test.go
- pkg/service/ecloud/service_region.go
- pkg/service/ecloud/service_region_test.go
- pkg/service/ecloud/service_router.go
- pkg/service/ecloud/service_router_test.go
- pkg/service/ecloud/service_solution.go
- pkg/service/ecloud/service_vpn.go
- pkg/service/ecloud/service_vpn_test.go
> Ecloud v2 resources

- pkg/service/ecloud/request.go
- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_loadbalancercluster.go
- pkg/service/ecloud/service_loadbalancercluster_test.go
- pkg/service/ecloud/service_network.go
- pkg/service/ecloud/service_network_test.go
- pkg/service/ecloud/service_router.go
- pkg/service/ecloud/service_router_test.go
- pkg/service/ecloud/service_vpc.go
- pkg/service/ecloud/service_vpc_test.go
- pkg/service/ecloud/service_vpn.go
- pkg/service/ecloud/service_vpn_test.go
Adds missing eCloud v2 resources
> Missing ecloud v2 resources

- pkg/service/ecloud/request.go
- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_instance.go
- pkg/service/ecloud/service_instance_test.go
Adds support for adding and removing eCloud v2 instances
> add support for creating and deleting instances

- pkg/service/ddosx/request.go
This PR removes client-side validation for properties which aren't required
> remove validation from CreateRecordRequest

- .travis.yml
- pkg/service/ecloud/model.go
- pkg/service/ecloud/model_paginated_generated.go
- pkg/service/ecloud/model_response_generated.go
- pkg/service/ecloud/request.go
- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_instance.go
- pkg/service/ecloud/service_instance_test.go
Add missing eCloud VPC resources
> Ecloud vpc resources

- pkg/service/ecloud/error.go
- pkg/service/ecloud/model.go
- pkg/service/ecloud/model_paginated_generated.go
- pkg/service/ecloud/model_response_generated.go
- pkg/service/ecloud/request.go
- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_firewallpolicy.go
- pkg/service/ecloud/service_firewallpolicy_test.go
- pkg/service/ecloud/service_firewallrule.go
- pkg/service/ecloud/service_firewallrule_test.go
- pkg/service/ecloud/service_instance_test.go
- pkg/service/ecloud/service_network_test.go
- pkg/service/ecloud/service_router_test.go
Add in API changes for eCloud v2
> adding resources, updating requests to match API

- pkg/service/ecloud/error.go
- pkg/service/ecloud/request.go
- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_volume.go
- pkg/service/ecloud/service_volume_test.go
Adds support for managing ecloud v2 volumes
> add support for managing ecloud v2 volumes

- pkg/service/ecloud/request.go
- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_volume.go
- pkg/service/ecloud/service_volume_test.go
Adds ability to create eCloud v2 volumes
> Ecloud v2 volume creation

- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_instance.go
- pkg/service/ecloud/service_instance_test.go
Adds ecloud service method for retrieving an instance console session
> eCloud v2 - instance console

- pkg/service/ecloud/model.go
> Volume model

- pkg/service/ecloud/request.go
- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_volume.go
- pkg/service/ecloud/service_volume_test.go
- add AttachVolume and DetachVolume methods
> add attach / detach for volumes

- pkg/service/ecloud/model.go
> Add volume type

- pkg/service/ecloud/error.go
- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_task.go
- pkg/service/ecloud/service_task_test.go
Adds GetTask(s) eCloud service methods
> add task resource methods

- pkg/service/ecloud/model.go
- pkg/service/ecloud/request.go
needed to support network policies in TF
> add advanced networking to vpc request

- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_floatingip.go
- pkg/service/ecloud/service_floatingip_test.go
Update floating ip operations to return task references
> use tasks on fip operations

- pkg/service/ecloud/model.go
- pkg/service/ecloud/request.go
- add availability_zone_id to `floating_ip` model 
- add availability_zone_id to `CreateFloatingIPRequest`
> add availability_zone_id to floating  ip

- pkg/connection/connection.go
Sets timeout to sensible default of `120s`
> Set default connection timeout

- pkg/service/ecloud/error.go
- pkg/service/ecloud/model.go
- pkg/service/ecloud/model_paginated_generated.go
- pkg/service/ecloud/model_response_generated.go
- pkg/service/ecloud/request.go
- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_ipaddress.go
- pkg/service/ecloud/service_ipaddress_test.go
- pkg/service/ecloud/service_nic.go
- pkg/service/ecloud/service_nic_test.go
Surface network ip address resources
> add support for ecloud ip addresses

- pkg/service/ecloud/error.go
- pkg/service/ecloud/model.go
- pkg/service/ecloud/request.go
- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_affinityrule.go
- pkg/service/ecloud/service_affinityrule_test.go
- pkg/service/ecloud/service_affinityrulemember.go
- pkg/service/ecloud/service_affinityrulemember_test.go
add support for affinity rules and affinity rule members
> Affinity rules

- pkg/connection/helper.go
- pkg/connection/response.go
- pkg/service/ecloud/model.go
- pkg/service/ecloud/request.go
- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_image.go
- pkg/service/ecloud/service_image_test.go
- pkg/service/ecloud/service_instance.go
- pkg/service/ecloud/service_instance_test.go
Adds support for eCloud VPC private images
> Ecloud instance images

- pkg/connection/response.go
- pkg/connection/response_test.go
Wraps API response errors, as so that they can be consumed
> Wrap API response errors

- pkg/service/ecloud/service_instance_test.go
- pkg/service/loadbalancer/error.go
- pkg/service/loadbalancer/model.go
- pkg/service/loadbalancer/service.go
- pkg/service/loadbalancer/service_deployment.go
- pkg/service/loadbalancer/service_deployment_test.go
> LB deployments

- pkg/service/ecloud/request.go
- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_instance.go
- pkg/service/ecloud/service_instance_test.go
Implementation of eCloud guest execution script API
> Adds eCloud guest execution script functionality

- pkg/service/account/service.go
Added appID string to UpdateApplication interface
> Added parameter to UpdateApplication interface

- pkg/service/account/service.go
- pkg/service/account/service_application.go
- pkg/service/account/service_application_test.go
DeleteApplicationRestrictions function added which just passes a blank api request interface to the API which clears IP restrictions an a given application. 
Also written tests + fixed a bug in one test based on a previous change.
> Added DeleteApplicationRestrictions function + testing

- pkg/service/account/service.go
- pkg/service/account/service_application.go
- pkg/service/account/service_application_test.go
- test coverage improved to include testing for UpdateApplication function
- DeleteApplicationServices function added
> Improved test coverage and implemented DeleteApplicationServices

- pkg/service/ecloud/model.go
- pkg/service/ecloud/request.go
- pkg/service/ecloud/service.go
- pkg/service/ecloud/service_monitoringgateway.go
- pkg/service/ecloud/service_monitoringgateway_test.go
- pkg/service/ecloud/service_nic.go
- pkg/service/ecloud/service_nic_test.go
added create, patch and delete functions to both nics & mgws
> added additional features for nics & mgws
